class_name EnemyConfig
extends "res://src/resources/stats_config.gd"

## One Enemy Kind's typed config (gADR-0003): the three orthogonal taxonomy axes
## (Faction x Tier x Archetype), the stat block, the blockout, and the
## Archetype-AI params.
##
## EXTENDS StatsConfig (by path — no editor class cache in this never-imported
## project), so an EnemyConfig IS its own stat block: it feeds
## CombatSystem.compute_damage directly as attacker or defender — the symmetric
## damage-formula contract (gADR-0001) with no second stats object per kind.
##
## This Resource is a DERIVED artifact: one data/generated/enemy_<kind>.tres per
## kind in the authoritative data/json/enemies_config.json, regenerated by
## scripts/build_config.py (validated against enemies_config.schema.json). Never
## hand-edit the generated .tres or hardcode these values (gADR-0000). The
## @export fields carry NO default literals on purpose (see PlayerConfig).

# Taxonomy axes (GAME-CONTEXT.md). Faction is cosmetic/lore; Tier drives the
# stat budget (data, not code); Archetype selects the AI behavior branch.
@export var faction: String
@export var tier: String
@export var archetype: String

# Blockout: the enemy block's color (Faction flavor) and size (Tier read at a
# glance, per the GDD scale-ratio rules).
@export var color: Color
@export var size: Vector2

# Motion: horizontal steering speed plus the vertical fall params (a
# CharacterBody2D since S4; a floating kind would set gravity 0).
@export var move_speed: float
@export var gravity: float
@export var max_fall_speed: float

# Archetype-AI params (EnemyAI, gADR-0003): the Aggro Range gate, the attack
# range/cooldown gate, and the Steering Band [keep_range_min, keep_range_max]
# the AI holds (Melee: min 0 = never back off; Ranged: a standoff band).
@export var aggro_range: float
@export var attack_range: float
@export var attack_cooldown: float
@export var keep_range_min: float
@export var keep_range_max: float

# Attack-telegraph juice: a scale punch tweened back to normal (the S4 sibling
# of S1's landing squash).
@export var attack_squash: Vector2
@export var attack_tween_duration: float

# Ranged-only: the enemy bolt's blockout + motion (schema requires these iff
# archetype == "ranged"; other kinds leave them at type defaults, never read).
@export var projectile_color: Color
@export var projectile_size: Vector2
@export var projectile_speed: float
@export var projectile_lifetime: float
@export var projectile_spawn_offset: Vector2

# S6a Kill reward (gADR-0004): what defeating this kind awards the Player.
# DERIVED per kind by the builder from the authoritative per-Tier reward table
# (enemies_config.json's `tiers`, keyed by this kind's `tier`) — the runtime
# reads dumb fields; retuning a Tier's reward stays a single JSON edit.
@export var exp_reward: float
@export var gold_reward: float

# S6b Drop table (gADR-0006): what defeating this kind may leave behind as
# Pickups — an Array of {"item": String, "amount": int, "chance": float}
# entries, each rolled independently (EconomySystem.resolve_drops). DERIVED
# per kind from the same per-Tier table as the rewards above.
@export var drop_table: Array
